Models/Pedido.cs
namespace MVC_ComponenteCodeFirst.Models
{
    public class Pedido
    {
        public int Id { get; set; }

        public string Name { get; set; } = "";

        public ICollection<Ordenador> Ordenadores { get; set;} = new List<Ordenador>();

        public double Precio { get; set; } = 0;
    }
}

Controllers/OrdenadoresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVC_ComponenteCodeFirst.Data;
using MVC_ComponenteCodeFirst.Models;
using MVC_ComponenteCodeFirst.Services;
using MVC_ComponenteCodeFirst.CrossCuting.Logging;

namespace MVC_ComponenteCodeFirst.Controllers
{
    public class OrdenadoresController : Controller
    {
        private readonly IRepositorioOrdenador _repositorio;
        private readonly ILoggerManager _logger;
        private readonly IRepositorioComponente _repositorioComponente;

        public OrdenadoresController(IRepositorioComponente repositorioComponente,IRepositorioOrdenador repositorio, ILoggerManager loger)
        {
            _repositorio = repositorio;
            _logger = loger;
            _repositorioComponente = repositorioComponente;
        }

        // GET: Ordenadores
        public async Task<IActionResult> Index()
        {
            return View("Index", await _repositorio.GetAll());
        }
        public async Task<IActionResult> Add(int id)
        {
            ViewData["ComponenteId"] = new SelectList(await _repositorioComponente.GetByNull(), "Id", "Descripcion");
            ViewData["OrdenadorId"] = id;
            return View();
        }
        // GET: Ordenadores/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var ordenador = await _repositorio.Find(id);
            return ordenador == null ? View("Index") : View("Details", ordenador) ;
        }

        // GET: Ordenadores/Create
        public IActionResult Create()
        {
            this._logger.LogInfo("Mostrando ventana de creacion de ordenador");
            return View("Create");
        }

        // POST: Ordenadores/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id, Name")] Ordenador ordenador)
        {
            try
            {
                await _repositorio.Add(ordenador);
                return View("Index", await _repositorio.GetAll());
            }
            catch
            {
                _logger.LogError("No se ha podido crear el ordenador");
                return View("Create");
            }
        }

        // GET: Ordenadores/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            try
            {
                return View("Edit", await _repositorio.Find(id));
            }
            catch
            {
                _logger.LogError("No se ha encontrado el componente");
                return View();
            }
        }

        // POST: Ordenadores/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Ordenador ordenador)
        {
 
            await _repositorio.Update(id, ordenador);
            return View("Index", await _repositorio.GetAll());

        }

        [HttpPost]
        public async Task<IActionResult> EditPedidoId(int Id, int PedidoId)
        {
            await _repositorio.UpdatePedidoId(Id,PedidoId);
            return View("Index", await _repositorio.GetAll());
        }

        public async Task<IActionResult> EditPedidoId(int Id)
        {
            await _repositorio.UpdatePedidoId(Id, null);
            return View("Index", await _repositorio.GetAll());
        }

        // GET: Componentes/Delete/5
        public async Task<IActionResult> Delete(int id)
        {

            var ordenador = await _repositorio.Find(id);
            if (ordenador == null)
            {
                _logger.LogError("No se ha encontrado el ordenador");
                return View("Index", await _repositorio.GetAll());
            }

            return View("Delete", ordenador);
        }

        // POST: Componentes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _repositorio.Delete(id);
            return View("Index", await _repositorio.GetAll());
        }
    }
}

Controllers/PedidosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVC_ComponenteCodeFirst.Data;
using MVC_ComponenteCodeFirst.Models;
using MVC_ComponenteCodeFirst.Services;

namespace MVC_ComponenteCodeFirst.Controllers
{
    public class PedidosController : Controller
    {
        private readonly IRepositorioOrdenador _repositorioOrdenador;
        private readonly IRepositorioPedido _repositorioPedido;

        public PedidosController(IRepositorioPedido repositorioPedido,IRepositorioOrdenador repositorioOrdenador)
        {
            _repositorioOrdenador = repositorioOrdenador;
            _repositorioPedido = repositorioPedido;
        }

        // GET: Pedidos
        public async Task<IActionResult> Index()
        {
            return View("Index", await _repositorioPedido.GetAll());
        }

        public async Task<IActionResult> Details(int id)
        {
            var pedido = await _repositorioPedido.Find(id);
            return pedido == null ? View("Index") : View("Details", pedido);
        }

        public async Task<IActionResult> Add(int id)
        {
            ViewData["OrdenadorId"] = new SelectList(await _repositorioOrdenador.GetByNull(), "Id", "Name");
            ViewData["PedidoId"] = id;
            return View("Add");
        }

        // GET: Pedidos/Create
        public IActionResult Create()
        {
            return View("Create");
        }

        // POST: Pedidos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create( Pedido pedido)
        {
            try 
            {
                await _repositorioPedido.Add(pedido);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(pedido);
            }
            
        }

        // GET: Pedidos/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            var pedido = await _repositorioPedido.Find(id);
            return View(pedido);
        }

        // POST: Pedidos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _repositorioPedido.Delete(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

ViewComponents/DetailsComponentesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MVC_ComponenteCodeFirst.Models;

namespace MVC_ComponenteCodeFirst.ViewModel
{
    public class DetailsComponentesViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(IEnumerable<Componente> lista)
        {
            return await Task.FromResult(View("Default", lista));
        }
    }
}

Views/Pedidos/Add.cshtml
@model MVC_ComponenteCodeFirst.Models.Ordenador

@{
    ViewData["Title"] = "Add";
}

<h1>Add</h1>

<h4>Pedido</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-controller="Ordenadores" asp-action="EditPedidoId">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label">Add Pc</label>
                <select asp-for="Id" class ="form-control" asp-items="ViewBag.OrdenadorId"></select>
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <input type="hidden" name="PedidoId" value="@ViewData["PedidoId"]" />
            <div class="form-group">
                <input type="submit" value="Add" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Pedidos/Create.cshtml
@model MVC_ComponenteCodeFirst.Models.Pedido

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Pedido</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Pedidos/Delete.cshtml
@model MVC_ComponenteCodeFirst.Models.Pedido

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Pedido</h4>
    <hr />
    <dl class="row">
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Pedidos/Details.cshtml
@model MVC_ComponenteCodeFirst.Models.Pedido

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>@Html.DisplayFor(model => model.Name)</h4>
    <h6>Precio: @Model.Precio</h6>
    <hr />
    
        @foreach(var item in Model.Ordenadores)
        {
        <table class="table">
            <tr>
                <th>Ordenador: </th>
                <td>@item.Name</td>
            </tr>
            <tr>
                <th>Precio: </th>
                <td>@item.Precio</td>
            </tr>
            <tr>
                <th>
                    Componentes
                </th>
                <td>
                    @await Component.InvokeAsync("DetailsComponentes", new{lista = item.Componentes})
                </td>
            </tr>
        </table>
        }
        
    
</div>

Views/Pedidos/Edit.cshtml
@model MVC_ComponenteCodeFirst.Models.Pedido

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Pedido</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Pedidos/Index.cshtml
@model IEnumerable<MVC_ComponenteCodeFirst.Models.Pedido>

@{
    ViewData["Title"] = "Index";
}

<h1>Pedidos</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Precio</th>
            <th>Ordenadores</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @item.Name
            </td>
            <td>
                @item.Precio
            </td>
            <td>
            @foreach(var item1 in item.Ordenadores)
                {
                   @item1.Name
                   <a class="link-danger" asp-controller="Ordenadores" asp-action="EditPedidoId" asp-route-id="@item1.Id"> X </a>
                   <br />
                }
            </td>
            <td>
                <a asp-controller="Pedidos" asp-action="Add" asp-route-id="@item.Id">Add Pc</a>
            </td>
            <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pen" viewBox="0 0 16 16">
                            <path d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001zm-.644.766a.5.5 0 0 0-.707 0L1.95 11.756l-.764 3.057 3.057-.764L14.44 3.854a.5.5 0 0 0 0-.708l-1.585-1.585z" />
                        </svg>
                    </a> |
                    <a asp-action="Details" asp-route-id="@item.Id">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-list-columns-reverse" viewBox="0 0 16 16">
                            <path fill-rule="evenodd" d="M0 .5A.5.5 0 0 1 .5 0h2a.5.5 0 0 1 0 1h-2A.5.5 0 0 1 0 .5Zm4 0a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1h-10A.5.5 0 0 1 4 .5Zm-4 2A.5.5 0 0 1 .5 2h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1-.5-.5Zm4 0a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5Zm-4 2A.5.5 0 0 1 .5 4h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1-.5-.5Zm4 0a.5.5 0 0 1 .5-.5h11a.5.5 0 0 1 0 1h-11a.5.5 0 0 1-.5-.5Zm-4 2A.5.5 0 0 1 .5 6h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1-.5-.5Zm4 0a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 0 1h-8a.5.5 0 0 1-.5-.5Zm-4 2A.5.5 0 0 1 .5 8h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1-.5-.5Zm4 0a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 0 1h-8a.5.5 0 0 1-.5-.5Zm-4 2a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1-.5-.5Zm4 0a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1h-10a.5.5 0 0 1-.5-.5Zm-4 2a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1-.5-.5Zm4 0a.5.5 0 0 1 .5-.5h6a.5.5 0 0 1 0 1h-6a.5.5 0 0 1-.5-.5Zm-4 2a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1-.5-.5Zm4 0a.5.5 0 0 1 .5-.5h11a.5.5 0 0 1 0 1h-11a.5.5 0 0 1-.5-.5Z" />
                        </svg>
                    </a> |
                    <a class="link-danger" asp-action="Delete" asp-route-id="@item.Id">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6Z" />
                            <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1ZM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118ZM2.5 3h11V2h-11v1Z" />
                        </svg>
                    </a>
  
            </td>
        </tr>
}
    </tbody>
</table>