Models/Componente.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MVC_ComponenteCodeFirst.Models;

public class Componente
{
    public int Id { get; set; }
    [Required]
    [Range(0, 2)]
    public int TipoComponente { get; set; }
    [StringLength(150, ErrorMessage = "No en rango", MinimumLength = 10)]
    public string Descripcion { get; set; } = "";
    [Required]
    [StringLength(20,ErrorMessage ="No en rango", MinimumLength =1)]
    public string Serie { get; set; } = "";
    [Required]
    [Range(minimum: 0, maximum: 99999, ErrorMessage = "Ha introducido un precio demasiado grande")]
    public double Precio { get; set; }
    [Range(minimum: 0, maximum: 99999, ErrorMessage = "Ha introducido una cantidad demasiado grande")]
    public int Calor { get; set; }
    [Range(minimum: 0, maximum: 999999999999999, ErrorMessage = "Ha introducido un almacenamiento demasiado grande")]
    public long Almacenamiento { get; set; }
    [Range(minimum: 0, maximum: 99999, ErrorMessage = "Ha introducido una cantidad demasiado grande")]
    public int Cores { get; set; }

    public int? OrdenadorId { get; set; }
    public virtual Ordenador? Ordenador { get; set; } = null;
}

Controllers/ComponentesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Xml.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.EntityFrameworkCore;
using MVC_ComponenteCodeFirst.CrossCuting.Logging;
using MVC_ComponenteCodeFirst.Data;
using MVC_ComponenteCodeFirst.Models;
using MVC_ComponenteCodeFirst.Services;
using MVC_ComponenteCodeFirst.Services.RepoByApi;
//using TiendaOrdenadores;
//using TiendaOrdenadores;

namespace MVC_ComponenteCodeFirst.Controllers
{
    public class ComponentesController : Controller
    {
        private readonly IRepositorioComponente _repositorio;
        private readonly ILoggerManager _logger;
        private readonly IRepositorioOrdenador _repositorioOrdenador;
        //private readonly IValidadorComponente validador;
        public ComponentesController(IRepositorioComponente repositorio, ILoggerManager logger,
            IRepositorioOrdenador repOrdenador)
        {
            _repositorio = repositorio;
            _logger = logger;
            _repositorioOrdenador = repOrdenador;
        }

        // GET: Componentes
        public async Task<IActionResult> Index()
        {
            _logger.LogInfo("Mostrando todos los componentes");
            var componentes = await _repositorio.GetAll();
            return View("Index", componentes);
        }

        // GET: Componentes/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var componente = await _repositorio.Find(id);
            return View("Details", componente);
        }
        public IActionResult CreateByOrdenador(int OrdenadorId)
        {
            ViewData["OrdenadorId"] = OrdenadorId;
            _logger.LogInfo("Mostrando ventana de creacion");
            return View("Create");
        }

        // GET: Componentes/Create
        public async Task<IActionResult> Create()
        {
            ViewData["OrdenadorId"] = new SelectList(await _repositorioOrdenador.GetAll(), "Id", "Name");
            _logger.LogInfo("Mostrando ventana de creacion");
            return View("Create");
        }

        // POST: Componentes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,TipoComponente,Descripcion,Serie,Precio,Calor,Almacenamiento,Cores,OrdenadorId")] Componente componente)
        {
            try
            {
                await _repositorio.Add(componente);

                if(componente.OrdenadorId == null) 
                    return View("Index", await _repositorio.GetAll());

                return RedirectToAction("Index", "Ordenadores", _repositorioOrdenador.GetAll());

            }
            catch
            {
                _logger.LogError("No se ha podido crear el componente");
                return View("Create");
            }
        }

        // GET: Componentes/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            try
            {
                ViewData["OrdenadorId"] = new SelectList(await _repositorioOrdenador.GetAll(), "Id", "Name");
                return View("Edit", await _repositorio.Find(id));
            }
            catch
            {
                _logger.LogError("No se ha encontrado el componente");
                return View();
            }
        }


        // POST: Componentes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,TipoComponente,Descripcion,Serie,Precio,Calor,Almacenamiento,Cores,OrdenadorId")] Componente componente)
        {
            await _repositorio.Update(id, componente);
            return View ("Index",await _repositorio.GetAll());
            
        }

        [HttpPost]
        public async Task<IActionResult> EditOrdenadorId(int Id, int OrdenadorId)
        {
            await _repositorio.UpdateOrdenadorId(Id, OrdenadorId);
            return RedirectToAction("Index", "Ordenadores", _repositorioOrdenador.GetAll());
        }

        public async Task<IActionResult> EditOrdenadorId(int Id)
        {
            await _repositorio.UpdateOrdenadorId(Id, null);
            return RedirectToAction("Index", "Ordenadores", _repositorioOrdenador.GetAll());
        }

        // GET: Componentes/Delete/5
        public async Task<IActionResult> Delete(int id)
        {

            var componente = await _repositorio.Find(id);
            if (componente == null)
            {
                _logger.LogError("No se ha encontrado el componente");
                return View("Index",await _repositorio.GetAll());
            }

            return View("Delete",componente);
        }

        // POST: Componentes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _repositorio.Delete(id);
            return View("Index", await _repositorio.GetAll());
        }

        //private bool ComponenteExists(int id)
        //{
        //  return (_context.componentes?.Any(e => e.ID == id)).GetValueOrDefault();
        //}
    }
}

ViewComponents/Componentes/ComponenteViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MVC_ComponenteCodeFirst.Models;
using MVC_ComponenteCodeFirst.Services;

namespace MVC_ComponenteCodeFirst.ViewComponents.Componentes
{
    public class ComponenteViewComponent : ViewComponent
    {
        public ComponenteViewComponent()
        {
        }
        public async Task<IViewComponentResult> InvokeAsync(Componente componente)
        {
            return await Task.FromResult(View("Default", componente));
        }
    }
}

ViewComponents/ListaComponentesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MVC_ComponenteCodeFirst.Models;
using MVC_ComponenteCodeFirst.Services;

namespace MVC_ComponenteCodeFirst.ViewModel
{
    public class ListaComponentesViewComponent : ViewComponent
    {

        public async Task<IViewComponentResult> InvokeAsync(IEnumerable<Componente> lista)
        {
            return await Task.FromResult(View("Default", lista));
        }
    }
}

Views/Componentes/Create.cshtml
@model MVC_ComponenteCodeFirst.Models.Componente

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Componente</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                @*<label asp-for="TipoComponente" class="control-label"></label>
                <input asp-for="TipoComponente" class="form-control" />
                <span asp-validation-for="TipoComponente" class="text-danger"></span>*@
                <label asp-for="TipoComponente" class="control-label"></label>
                <select asp-for="TipoComponente" class="form-control" asp-items="ViewBag.TipoComponente">
                    @foreach (var item in Enum.GetValues(typeof(TipoComponente)))
                {
                    <option value="@Convert.ToInt32(item)">@item</option>
                }
                </select>
                

            </div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <textarea asp-for="Descripcion" class="form-control"></textarea>
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Serie" class="control-label"></label>
                <input asp-for="Serie" class="form-control" />
                <span asp-validation-for="Serie" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Precio" class="control-label"></label>
                <input asp-for="Precio" class="form-control" />
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Calor" class="control-label"></label>
                <input asp-for="Calor" class="form-control" />
                <span asp-validation-for="Calor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Almacenamiento" class="control-label"></label>
                <input asp-for="Almacenamiento"  class="form-control" />
                <span asp-validation-for="Almacenamiento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cores" class="control-label"></label>
                <input asp-for="Cores" class="form-control" />
                <span asp-validation-for="Cores" class="text-danger"></span>
            </div>
            @if (ViewData["OrdenadorId"] is int)
            {
                <div class="form-group">
                    <label asp-for="OrdenadorId" class="control-label"></label>
                    <input name="OrdenadorId" class="form-control" value=" @ViewData["OrdenadorId"]" readonly  />
                    <span asp-validation-for="OrdenadorId" class="text-danger"></span>

                </div>
            }
            
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Componentes/Delete.cshtml
@model MVC_ComponenteCodeFirst.Models.Componente

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Componente</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TipoComponente)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TipoComponente)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Serie)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Serie)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Precio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Precio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Calor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Calor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Almacenamiento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Almacenamiento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cores)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cores)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ordenador)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ordenador.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Componentes/Details.cshtml
@model MVC_ComponenteCodeFirst.Models.Componente

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Componente</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TipoComponente)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TipoComponente)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Serie)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Serie)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Precio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Precio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Calor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Calor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Almacenamiento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Almacenamiento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cores)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cores)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Componentes/Edit.cshtml
@model MVC_ComponenteCodeFirst.Models.Componente

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Componente</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="TipoComponente" class="control-label"></label>
                <select asp-for="TipoComponente" class="form-control" asp-items="ViewBag.TipoComponente">
                    @foreach (var item in Enum.GetValues(typeof(TipoComponente)))
                    {
                        <option value="@Convert.ToInt32(item)">@item</option>
                    }
                </select>


            </div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <textarea asp-for="Descripcion" class="form-control"></textarea>
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Serie" class="control-label"></label>
                <input asp-for="Serie" class="form-control" />
                <span asp-validation-for="Serie" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Precio" class="control-label"></label>
                <input asp-for="Precio" class="form-control" />
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Calor" class="control-label"></label>
                <input asp-for="Calor" class="form-control" />
                <span asp-validation-for="Calor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Almacenamiento" class="control-label"></label>
                <input asp-for="Almacenamiento" class="form-control" />
                <span asp-validation-for="Almacenamiento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cores" class="control-label"></label>
                <input asp-for="Cores" class="form-control" />
                <span asp-validation-for="Cores" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OrdenadorId" class="control-label"></label>
                <select asp-for="OrdenadorId" class="form-control" asp-items="ViewBag.OrdenadorId">
                    <option value=null></option>
                </select>
                <span asp-validation-for="OrdenadorId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Componentes/Index.cshtml
@model IEnumerable<MVC_ComponenteCodeFirst.Models.Componente>

@{
    ViewData["Title"] = "Index";
}

<h1>Lista de Componentes</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th class="text-secondary">
                @Html.DisplayNameFor(model => model.TipoComponente)
            </th>
            <th class="text-secondary">
                @Html.DisplayNameFor(model => model.Descripcion)
            </th>
            <th class="text-secondary">
                @Html.DisplayNameFor(model => model.Serie)
            </th>
            <th class="text-secondary">
                @Html.DisplayNameFor(model => model.Precio)
            </th>
            <th class="text-secondary">
                @Html.DisplayNameFor(model => model.Calor)
            </th>
            <th class="text-secondary">
                @Html.DisplayNameFor(model => model.Almacenamiento)
            </th>
            <th class="text-secondary">
                @Html.DisplayNameFor(model => model.Cores)
            </th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        
        @foreach (var item in Model)
        {
            <tr>
                @await Component.InvokeAsync("Componente", new {componente =item})
    

                <td>
                    @if (item.OrdenadorId == null)
                    {
                        <a asp-action="Edit" asp-route-id="@item.Id">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pen" viewBox="0 0 16 16">
                                <path d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001zm-.644.766a.5.5 0 0 0-.707 0L1.95 11.756l-.764 3.057 3.057-.764L14.44 3.854a.5.5 0 0 0 0-.708l-1.585-1.585z" />
                            </svg>
                        </a>
                        @(" | ")

                        <a class="link-danger" asp-action="Delete" asp-route-id="@item.Id">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6Z" />
                                <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1ZM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118ZM2.5 3h11V2h-11v1Z" />
                            </svg>
                        </a>
                        @(" | ")
                    }


                    <a asp-action="Details" asp-route-id="@item.Id">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-list-columns-reverse" viewBox="0 0 16 16">
                            <path fill-rule="evenodd" d="M0 .5A.5.5 0 0 1 .5 0h2a.5.5 0 0 1 0 1h-2A.5.5 0 0 1 0 .5Zm4 0a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1h-10A.5.5 0 0 1 4 .5Zm-4 2A.5.5 0 0 1 .5 2h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1-.5-.5Zm4 0a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5Zm-4 2A.5.5 0 0 1 .5 4h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1-.5-.5Zm4 0a.5.5 0 0 1 .5-.5h11a.5.5 0 0 1 0 1h-11a.5.5 0 0 1-.5-.5Zm-4 2A.5.5 0 0 1 .5 6h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1-.5-.5Zm4 0a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 0 1h-8a.5.5 0 0 1-.5-.5Zm-4 2A.5.5 0 0 1 .5 8h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1-.5-.5Zm4 0a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 0 1h-8a.5.5 0 0 1-.5-.5Zm-4 2a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1-.5-.5Zm4 0a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1h-10a.5.5 0 0 1-.5-.5Zm-4 2a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1-.5-.5Zm4 0a.5.5 0 0 1 .5-.5h6a.5.5 0 0 1 0 1h-6a.5.5 0 0 1-.5-.5Zm-4 2a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1-.5-.5Zm4 0a.5.5 0 0 1 .5-.5h11a.5.5 0 0 1 0 1h-11a.5.5 0 0 1-.5-.5Z" />
                        </svg>
                    </a> |

                </td>
            </tr>
        }
        

        
    </tbody>
</table>
@*@await Component.InvokeAsync("ListaComponentes", new {lista = Model})*@